import type { Metadata } from "next";
import { Merriweather, JetBrains_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/header";
import Footer from "./component/footer";
import { ThemeProvider } from "next-themes";
import { BlogProvider } from "./context/BlogContext";

const merriWeather = Merriweather({
  variable: "--font-me",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetBrains = JetBrains_Mono({
  variable: "--font-jbm",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="dark"
      suppressHydrationWarning
    >
      <body
        className={`${merriWeather.variable} ${jetBrains.variable} ${inter.variable}  antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <BlogProvider>
            <Header />
            {children}
            <Footer />
          </BlogProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
